"""Export where every fruit card hangs, at every game count, for the app.

The orchard flies a game dropped on a tree to the exact spot its card will
pop in. That spot moves as the tree grows (each card follows its leaf
cluster), so the app needs it per game count, measured from the same renders
fit.py solves against, not guessed.

  python rive/tree/export_slots.py

Writes app/lib/ui/orchard/fruit_slots.g.dart: kFruitCentres[n - 1][i] is card
i's centre (artboard units) and scale on a tree holding n games. Then restores
the real scene.rml (measure() writes a debug build).
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fit as F  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "app", "lib", "ui", "orchard", "fruit_slots.g.dart")


def main():
    m = F.measure()
    try:
        cards = json.load(open(os.path.join(HERE, "fruit.json")))["cards"]
        rows = []
        for n in range(1, F.SLOTS + 1):
            k = F.blend(n)
            sc = F.EARLY_SCALE + (1 - F.EARLY_SCALE) * k
            cells = []
            for i in range(n):
                c = cards[i]
                _, _, r = F.card_rect(m, n, c["cluster_name"], c["a"], c["b"], i)
                cells.append(f"({(r[0] + r[2]) / 2:.1f}, {(r[1] + r[3]) / 2:.1f}, {sc:.3f})")
            rows.append("  [" + ", ".join(cells) + "],")
        dart = (
            "// GENERATED by rive/tree/export_slots.py from renders of the real tree.\n"
            "// Do not edit: re-run the script after fruit.json or the tree changes.\n"
            "//\n"
            "// kFruitCentres[n - 1][i]: card i's centre (x, y) in artboard units and its\n"
            "// scale (x the 40x53 card) on a tree holding n games.\n\n"
            "const List<List<(double, double, double)>> kFruitCentres = [\n"
            + "\n".join(rows) + "\n];\n")
        with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(dart)
        print("wrote", os.path.normpath(OUT))
    finally:
        subprocess.run([sys.executable, os.path.join(HERE, "build_tree.py")], check=True)


if __name__ == "__main__":
    main()
