// Generated by `dart run flutter_scene:init`. Edits outside the
// flutter_scene:init markers below survive a re-run.
//
// package:hooks arrives transitively through flutter_scene and is declared as a
// dev_dependency, but `hook/` is not one of the directories the lint treats as
// dev-only, so it reports anyway. Ignored rather than promoted to a real
// dependency, because this file never ships in the app -- and check.ps1 rule 14
// fails the build on ANY analyzer output.
// ignore_for_file: depend_on_referenced_packages
import 'package:flutter_scene/build_hooks.dart';
import 'package:hooks/hooks.dart';

void main(List<String> args) async {
  await build(args, (input, output) async {
// flutter_scene:init:start
    // Import .glb and .fscene sources under assets/, loadable by source path
    // with loadScene (and hot-reloadable). A no-op when there are no scenes.
    buildScenes(buildInput: input, buildOutput: output);
    // Compile .fmat materials under assets/, loadable by source path with
    // loadFmatMaterial (and hot-reloadable). A no-op when there are none.
    await buildMaterials(buildInput: input, buildOutput: output);
// flutter_scene:init:end
  });
}
